# -*- coding: utf-8 -*-
"""SV_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17CJnFMZtBfY_0b0m4p9ASVow57Xd41zV
"""


import kagglehub

# Tải dataset về
path = kagglehub.dataset_download("mrankitarya/underwater-audio-dataset")

print("Done. Path:", path)

import os
print(os.listdir(path))

import os

data_folder = os.path.join(path, 'DDDDD')

# 1. Kiểm tra xem thư mục có tồn tại không
if os.path.exists(data_folder):
    # 2. Liệt kê TẤT CẢ các file có trong thư mục (không lọc đuôi .wav)
    all_files = os.listdir(data_folder)
    print("Existing file/folder in 'DDDDD':", all_files)

    # 3. Kiểm tra xem có thư mục con nào khác không
    for item in all_files:
        item_path = os.path.join(data_folder, item)
        if os.path.isdir(item_path):
            print(f"Findout: {item}")
            # Nếu có thư mục con, liệt kê file bên trong đó
            print(f"File in {item}: {os.listdir(item_path)}")
else:
    print("Cannot find folder 'DDDDD'. Please check again!")

import os

data_folder = os.path.join(path, 'DDDDD')

# Hàm đệ quy để lấy tất cả file có đuôi .wav
def get_all_wav_files(directory):
    wav_files = []
    for root, dirs, files in os.walk(directory):
        for file in files:
            if file.lower().endswith('.wav'):
                wav_files.append(os.path.join(root, file))
    return wav_files

all_wav_files = get_all_wav_files(data_folder)
print(f"Total {len(all_wav_files)} audio file.")

# Kiểm tra xem có file nào không
if len(all_wav_files) > 0:
    print("Example path:", all_wav_files[0])


import numpy as np
from scipy.signal import hilbert, butter, filtfilt
from scipy.stats import entropy
from scipy.fftpack import fft
import pywt
from PyEMD import EMD
from vmdpy import VMD
from sklearn.svm import SVC
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as FDA

# ---------------------------- 1. DEMON Preprocessing ----------------------------
def demon_preprocess(signal: np.ndarray, fs: float, highpass_cutoff: float = 2000,
                     lowpass_cutoff: float = 100) -> np.ndarray:
    """
    DEMON (Detection of Envelope Modulation on Noise) preprocessing.
    """
    nyq = 0.5 * fs
    b_hp, a_hp = butter(4, highpass_cutoff / nyq, btype='high')
    high_freq_noise = filtfilt(b_hp, a_hp, signal)

    rectified = np.abs(high_freq_noise)

    b_lp, a_lp = butter(4, lowpass_cutoff / nyq, btype='low')
    envelope = filtfilt(b_lp, a_lp, rectified)

    return envelope

# ---------------------------- 2. BTWD Pre-filter (Bark Wavelet Thresholding) -----
def btwd_prefilter(signal: np.ndarray, fs: float, thr_m: float, wavelet='db4',
                   bark_bands: list = None) -> np.ndarray:
    """
    Pre-filter using Bark-scale wavelet thresholding.
    """
    coeffs = pywt.wavedec(signal, wavelet, level=5)
    threshold = thr_m * np.std(coeffs[-1])
    coeffs_thresh = [coeffs[0]] + [pywt.threshold(c, threshold, mode='soft') for c in coeffs[1:]]
    filtered = pywt.waverec(coeffs_thresh, wavelet)
    return filtered[:len(signal)]

# ---------------------------- 3. UPEMD (Uniform Phase EMD) -----------------------
def upemd_decompose(signal: np.ndarray, n_phases: int = 8, n_imfs: int = 6) -> np.ndarray:
    """
    Uniform Phase EMD – Fixed syntax error by removing '?' and adjusting masking calculation.
    """
    emd = EMD()
    fft_signal = np.abs(fft(signal))
    masking_freq = 0.1 * np.argmax(fft_signal) / len(signal)

    imfs_stack = []
    for phase in np.linspace(0, 2*np.pi, n_phases, endpoint=False):
        mask = 0.2 * np.std(signal) * np.cos(2*np.pi*masking_freq*np.arange(len(signal)) + phase)
        imfs = emd(signal + mask, max_imf=n_imfs)
        if len(imfs) < n_imfs:
            padding = np.zeros((n_imfs - len(imfs), len(signal)))
            imfs = np.vstack([imfs, padding])
        imfs_stack.append(imfs[:n_imfs])

    imfs_avg = np.mean(imfs_stack, axis=0)
    return imfs_avg

# ---------------------------- 4. Feature Extraction ------------------------------
def acf(signal: np.ndarray, max_lag: int = 100) -> float:
    corr = np.correlate(signal, signal, mode='full')
    corr = corr[len(corr)//2:]
    return np.max(corr[1:max_lag]) / corr[0] if corr[0] != 0 else 0

def permutation_entropy(signal: np.ndarray, order: int = 3, delay: int = 1) -> float:
    n = len(signal)
    permutations = []
    for i in range(n - order*delay):
        indices = np.argsort(signal[i:i+order*delay:delay])
        perm_code = tuple(indices)
        permutations.append(perm_code)
    _, counts = np.unique(permutations, return_counts=True)
    probs = counts / len(permutations)
    return -np.sum(probs * np.log2(probs + 1e-12))

def spectral_entropy(signal: np.ndarray, fs: float) -> float:
    import scipy.signal
    f, Pxx = scipy.signal.periodogram(signal, fs)
    Pxx_norm = Pxx / (np.sum(Pxx) + 1e-12)
    return -np.sum(Pxx_norm * np.log2(Pxx_norm + 1e-12))

def predictability_ratio(signal: np.ndarray, order: int = 10) -> float:
    from scipy.linalg import lstsq
    n = len(signal)
    X = np.array([signal[i:i+order] for i in range(n-order)])
    y = signal[order:]
    coeffs, _, _, _ = lstsq(X, y)
    y_pred = X @ coeffs
    mse_pred = np.mean((y - y_pred)**2)
    mse_orig = np.var(y)
    return 1 - mse_pred / (mse_orig + 1e-12)

def mutual_information(signal: np.ndarray, lag: int = 1, bins: int = 20) -> float:
    from sklearn.feature_selection import mutual_info_regression
    X = signal[:-lag].reshape(-1,1)
    y = signal[lag:]
    mi = mutual_info_regression(X, y, random_state=0)
    return mi[0]

def extract_features(imf: np.ndarray, fs: float) -> dict:
    return {
        'ACF': acf(imf),
        'PE': permutation_entropy(imf),
        'SE': spectral_entropy(imf, fs),
        'PR': predictability_ratio(imf),
        'MI': mutual_information(imf)
    }

# ---------------------------- 5. IMF Classifier (SVM / FDA) ----------------------
def train_imf_classifier(features_matrix, labels, method='svm', **kwargs):
    if method == 'svm':
        clf = SVC(kernel='rbf', probability=True, **kwargs)
    elif method == 'fda':
        clf = FDA(**kwargs)
    clf.fit(features_matrix, labels)
    return clf

def classify_imfs(imfs: np.ndarray, classifier, fs: float) -> np.ndarray:
    feat_list = [extract_features(imf, fs) for imf in imfs]
    feat_matrix = np.array([[f['ACF'], f['PE'], f['SE'], f['PR'], f['MI']] for f in feat_list])
    return classifier.predict(feat_matrix)

# ---------------------------- 6. BWTD Post-filter --------------------------------
def btwd_postfilter(signal: np.ndarray, fs: float, thr_aggressive: float = 0.7) -> np.ndarray:
    coeffs = pywt.wavedec(signal, 'db4', level=4)
    threshold = thr_aggressive * np.std(coeffs[-1])
    coeffs_thresh = [coeffs[0]] + [pywt.threshold(c, threshold, mode='soft') for c in coeffs[1:]]
    filtered = pywt.waverec(coeffs_thresh, 'db4')
    return filtered[:len(signal)]

# ---------------------------- 7. Signal Reconstruction ---------------------------
def reconstruct_signal(imfs: np.ndarray, decisions: np.ndarray, use_postfilter: bool = True, fs=None) -> np.ndarray:
    selected_imfs = [imfs[i] for i in range(len(decisions)) if decisions[i] == 1]
    if use_postfilter and fs is not None:
        selected_imfs = [btwd_postfilter(imf, fs) for imf in selected_imfs]
    if not selected_imfs:
        return np.zeros_like(imfs[0])
    return np.sum(selected_imfs, axis=0)

# ---------------------------- 8. HHT-VMD -----------------------------------------
def hht_vmd(x_rec: np.ndarray, fs: float, alpha: float = 2000, tau: float = 0,
            K: int = 5, DC: int = 0, init: int = 1, tol: float = 1e-7):
    u, u_hat, omega = VMD(x_rec, alpha, tau, K, DC, init, tol)
    inst_freqs = []
    inst_amps = []
    for mode in u:
        analytic = hilbert(mode)
        amp = np.abs(analytic)
        phase = np.unwrap(np.angle(analytic))
        freq = np.diff(phase) / (2*np.pi) * fs
        freq = np.append(freq, freq[-1])
        inst_freqs.append(freq)
        inst_amps.append(amp)

    n_time = len(x_rec)
    freq_axis = np.linspace(0, fs/2, 512)
    hilbert_spectrum = np.zeros((len(freq_axis), n_time))
    for k in range(K):
        for t in range(n_time):
            f = inst_freqs[k][t]
            if 0 < f < fs/2:
                idx = np.argmin(np.abs(freq_axis - f))
                hilbert_spectrum[idx, t] += inst_amps[k][t]**2
    return hilbert_spectrum, np.sum(hilbert_spectrum, axis=1), inst_freqs, inst_amps

# ---------------------------- Pipeline & Main ------------------------------------
def hilbert_huang_pipeline(signal: np.ndarray, fs: float, svm_classifier=None):
    env = demon_preprocess(signal, fs)
    env_filtered = btwd_prefilter(env, fs, thr_m=0.4)
    imfs = upemd_decompose(env_filtered, n_phases=8, n_imfs=6)
    if svm_classifier is None:
        energies = [np.sum(imf**2) for imf in imfs]
        threshold_energy = 0.5 * max(energies)
        decisions = np.array([1 if e > threshold_energy else 0 for e in energies])
    else:
        decisions = classify_imfs(imfs, svm_classifier, fs)
    x_rec = reconstruct_signal(imfs, decisions, use_postfilter=True, fs=fs)
    hilbert_spec, marginal_spec, _, _ = hht_vmd(x_rec, fs, K=4)
    return hilbert_spec, marginal_spec, x_rec, imfs, decisions

import pandas as pd
import librosa
import warnings
warnings.filterwarnings('ignore')

print("BEGIN PROCESSING REAL AUDIO DATA...")
all_features = []

# Lưu ý: Lúc mới test, coder có thể để all_wav_files[:50] để chạy thử 50 file cho nhanh.
# Khi nào code mượt thì bỏ [:50] đi để chạy hết 3803 file.
for i, file_path in enumerate(all_wav_files):
    try:
        # Đọc file âm thanh thô
        signal, fs = librosa.load(file_path, sr=10000, duration=2.0) # Lấy 2 giây đầu

        # Chạy qua Pipeline HHT và SVM của nhóm
        H_spec, M_spec, x_rec, imfs, dec = hilbert_huang_pipeline(signal, fs)

        # LOGIC GÁN NHÃN (LABEL) - Coder có thể tùy chỉnh lại theo nhu cầu
        label = 0  # 0: Ambient/Other (Nhiễu môi trường)
        if "cargo" in file_path.lower(): label = 1
        elif "passengership" in file_path.lower(): label = 2
        elif "tanker" in file_path.lower(): label = 3
        elif "tug" in file_path.lower(): label = 4

        # Gộp 512 đặc trưng (M_spec) và Nhãn vào chung 1 mảng
        row = list(M_spec) + [label]
        all_features.append(row)

        if (i+1) % 10 == 0:
            print(f"Đã xử lý {i+1} file...")
    except Exception as e:
        continue

# Xuất ra file CSV tổng hợp làm "thức ăn" cho 1D ResNet
df = pd.DataFrame(all_features)
df.to_csv('submarine_dataset.csv', index=False)
print("-> DONE file 'submarine_dataset.csv'")


